exports.TargetCustomerGroupError = {
  INVALID_BRAND: 'INVALID_BRAND',
  DISABLE_COFELYTICS: 'DISABLE_COFELYTICS',
  INVALID_BRANCHES: 'INVALID_BRANCHES',
  INVALID_REWARD_TIER: 'INVALID_REWARD_TIER',
  INVALID_STARTDATE: 'INVALID_STARTDATE',
  INVALID_DURATION: 'INVALID_DURATION',
  MISSING_PLATFORM_DATA: 'MISSING_PLATFORM_DATA',
  MISSING_SMS_OFFER_TEXT: 'MISSING_SMS_OFFER_TEXT',
  MISSING_EMAIL_OFFER_TEXT: 'MISSING_EMAIL_OFFER_TEXT',
  MISSING_PUSH_OFFER_TEXT: 'MISSING_PUSH_OFFER_TEXT',
  INVALID_IMAGES_URL: 'INVALID_IMAGES_URL',
  INVALID_TARGET_GROUP: 'INVALID_TARGET_GROUP',
  TRANSACTIONAL_ERROR: 'TRANSACTIONAL_ERROR',
  UNAUTHORIZED_PROCESS: 'UNAUTHORIZED_PROCESS',
  COFELYTICS_ALREADY_ENABLE: 'COFELYTICS_ALREADY_ENABLE',
  REQUEST_ALREADY_CREATED: 'REQUEST_ALREADY_CREATED',
  INVALID_REQUEST: 'INVALID_REQUEST',
  REQUEST_SAME_STATUS: 'REQUEST_SAME_STATUS',
};

exports.cofelyticsRequestStatus = {
  REQUESTED: 'REQUESTED',
  RESPONDED: 'RESPONDED'
};
