exports.saveSplashCategoryContentError = {
  MISSING_URL: 'MISSING_URL',
  UNAUTHORIZED_PROCESS: 'UNAUTHORIZED_PROCESS',
  INVALID_CATEGORY_ID: 'INVALID_CATEGORY_ID',
  ALREADY_EXIST: 'ALREADY_EXIST',
  INVALID_ID: 'INVALID_ID',
};

exports.platform = {
  IOS: 'IOS',
  ANDROID: 'ANDROID'
};

exports.language = {
  EN: 'EN',
  AR: 'AR'
};

exports.splashSize = {
  SMALL: 'SMALL',
  MEDIUM: 'MEDIUM',
  LARGE: 'LARGE',
  XLARGE: 'XLARGE',
};

exports.splashError = {
  NOT_FOUND: 'NOT_FOUND'
};

exports.splashCategoryContentType = {
  ANDROID_SMALL_EN: 'ANDROID_SMALL_EN',
  ANDROID_SMALL_AR: 'ANDROID_SMALL_AR',
  ANDROID_MEDIUM_EN: 'ANDROID_MEDIUM_EN',
  ANDROID_MEDIUM_AR: 'ANDROID_MEDIUM_AR',
  ANDROID_LARGE_EN: 'ANDROID_LARGE_EN',
  ANDROID_LARGE_AR: 'ANDROID_LARGE_AR',
  ANDROID_XLARGE_EN: 'ANDROID_XLARGE_EN',
  ANDROID_XLARGE_AR: 'ANDROID_XLARGE_AR',
  IOS_MEDIUM_EN: 'IOS_MEDIUM_EN',
  IOS_MEDIUM_AR: 'IOS_MEDIUM_AR',
  IOS_LARGE_EN: 'IOS_LARGE_EN',
  IOS_LARGE_AR: 'IOS_LARGE_AR',
  GENERAL: 'GENERAL',
};
