exports.contentCategoryStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DELETED: 'DELETED'
};

exports.contentCategoryError = {
  SLUG_ALREADY_EXISTS: 'SLUG_ALREADY_EXISTS',
  NO_DATA_TO_UPDATE: 'NO_DATA_TO_UPDATE',
  COMMON_CONTENT_CATEGORY_NOT_FOUND: 'COMMON_CONTENT_CATEGORY_NOT_FOUND',
  CATEGORY_NOT_UPDATED: 'CATEGORY_NOT_UPDATED',
  MISSING_COUNTRY_ID: 'MISSING_COUNTRY_ID',
};
