exports.tagSaveError = {
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_FIELD_NAME: 'MISSING_FIELD_NAME',
  MISSING_FIELD_DESCRIPTION: 'MISSING_FIELD_DESCRIPTION',
  NAME_ALREADY_EXIST: 'NAME_ALREADY_EXIST'
};
