exports.homePageSectionItemTypeEnum = {
  SEARCH_ITEM: 'SEARCH_ITEM',
  REORDER_ITEM: 'REORDER_ITEM',
  ORDER_TRACKING_ITEM: 'ORDER_TRACKING_ITEM',
  CAROUSEL_ITEM: 'CAROUSEL_ITEM',
  ICON_BUTTON_ITEM: 'ICON_BUTTON_ITEM',
  CARD_LIST_ITEM: 'CARD_LIST_ITEM',
  BORDERED_CARD_ITEM: 'BORDERED_CARD_ITEM',
  CATEGORY_ITEM: 'CATEGORY_ITEM',
};

exports.saveSectionErrorEnum = {
  NOT_EXIST: 'NOT_EXIST',
  MISSING_ARGUMENT: 'MISSING_ARGUMENT',
  ALREADY_EXIST_ITEM_TYPE_AND_REF_QUERY_ID: 'ALREADY_EXIST_ITEM_TYPE_AND_REF_QUERY_ID',
  SORT_ORDER_EXIST: 'SORT_ORDER_EXIST',
};


exports.saveSectionTypeEnum = {
  SECTION: 'SECTION',
  SECTION_SETTING: 'SECTION_SETTING'
};

exports.homePageSectionStatusEnum = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DELETED: 'DELETED',
};
