exports.brandLocationUnavailableItemsError = {
  BRAND_LOCATION_NOT_FOUND: 'BRAND_LOCATION_NOT_FOUND',
};

exports.menuItemSearchError = {
  INVALID_ARGS: 'INVALID_ARGS',
  INVALID_FILTERS: 'INVALID_FILTERS',
  INVALID_PAGING: 'INVALID_PAGING',
  MIN_LENGTH: 'MIN_LENGTH',
  MAX_LENGTH: 'MAX_LENGTH',
  INVALID_BRAND_LOCATION: 'INVALID_BRAND_LOCATION',
};

exports.menuItemStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
};
