exports.abandonedCartStatus = {
  ACTIVE: 'ACTIVE',
  TIMEOUT: 'TIMEOUT',
  CLEARED: 'CLEARED',
  COMPLETED: 'COMPLETED',
};

exports.abandonedCartSaveError = {
  INVALID_DEVICE_ID: 'INVALID_DEVICE_ID',
  INVALID_BASKET_ID: 'INVALID_BASKET_ID',
  INVALID_COUNTRY_ID: 'INVALID_COUNTRY_ID',
  INVALID_BRANCH_ID: 'INVALID_BRANCH_ID',
  INVALID_CART_ITEMS: 'INVALID_CART_ITEMS',
  ALREADY_ACTIVE_CART_EXISTS: 'ALREADY_ACTIVE_CART_EXISTS',
  INVALID_CART_ID: 'INVALID_CART_ID',
  ALREADY_EXISTS_BASKET_ID: 'ALREADY_EXISTS_BASKET_ID',
};

exports.abandonedCartInfo = {
  ACTIVE_CART_EXISTS: 'ACTIVE_CART_EXISTS',
  NO_ACTIVE_CART_EXISTS: 'NO_ACTIVE_CART_EXISTS',
};
