exports.cSubscriptionMenuItemsWithOptionsSaveError = {
  INVALID_BRAND: 'INVALID_BRAND',
  INVALID_OPTION: 'INVALID_OPTION',
  INVALID_SUBSCRIPTION: 'INVALID_SUBSCRIPTION',
  INVALID_MENU_ITEM: 'INVALID_MENU_ITEM',
  ALREADY_EXIST_MENU_ITEM: 'ALREADY_EXIST_MENU_ITEM',
  UNAUTHORIZED_PROCESS: 'UNAUTHORIZED_PROCESS'
};


exports.cSubscriptionMenuItemsWithOptionsDeleteError = {
  INVALID_ID: 'INVALID_ID',
  INVALID_SUBSCRIPTION_ID: 'INVALID_SUBSCRIPTION_ID',
  INVALID_BRAND_ID: 'INVALID_BRAND_ID',
  INVALID_MENU_ITEM_ID: 'INVALID_MENU_ITEM_ID',
  UNAUTHORIZED_PROCESS: 'UNAUTHORIZED_PROCESS'
};
