exports.categorySaveError = {
  INVALID_ID: 'INVALID_ID',
  INVALID_COUNTRY_ID: 'INVALID_COUNTRY_ID',
  INVALID_CATEGORY: 'INVALID_CATEGORY',
  CATEGORY_IDS_LENGTH_MUST_BE_GREATER_THAN_ZERO: 'CATEGORY_IDS_LENGTH_MUST_BE_GREATER_THAN_ZERO'
};
