exports.GiftCardByOrderIdError = {
  NOT_CREATED_YET: 'NOT_CREATED_YET',
  UNAUTHORIZED: 'UNAUTHORIZED',
};

exports.GiftCardCreateBulkError = {
  INVALID_NO_OF_CARDS: 'INVALID_NO_OF_CARDS',
  INVALID_COUNTRY: 'INVALID_COUNTRY',
  INVALID_TEMPLATE: 'INVALID_TEMPLATE',
  AMOUNT_OUT_OF_RANGE: 'AMOUNT_OUT_OF_RANGE',
  UNMATCHED_COUNTRY: 'UNMATCHED_COUNTRY',
  MIN_LIMIT_EXCEEDED: 'MIN_LIMIT_EXCEEDED',
  MAX_LIMIT_EXCEEDED: 'MAX_LIMIT_EXCEEDED',
};
