exports.branchArrivingTimeListError = {
  INVALID_INPUT: 'INVALID_INPUT',
  NOT_SUPPORTED: 'NOT_SUPPORTED',
  NO_VALUES: 'NO_VALUES',
  INVALID_FULFILLMENT: 'INVALID_FULFILLMENT',
  INVALID_COUNTRY_FOR_BRANCH: 'INVALID_COUNTRY_FOR_BRANCH',
};

exports.saveArrivedError = {
  ALREADY_ARRIVED: 'ALREADY_ARRIVED',
  NOT_SUPPORTED: 'NOT_SUPPORTED',
  INVALID_CUSTOMER: 'INVALID_CUSTOMER'
};

exports.popupStatusSaveError = {
  INVALID_CUSTOMER: 'INVALID_CUSTOMER',
  POPUP_ALREADY_SEEN: 'POPUP_ALREADY_SEEN'
};
