exports.cSubscriptionReferenceOrderType = {
  SUBSCRIPTION_ORDER: 'SUBSCRIPTION_ORDER',
  ORDER_SET: 'ORDER_SET',
};

exports.cSubscriptionActionType = {
  STARTED: 'STARTED',
  PAUSED: 'PAUSED',
  RESUMED: 'RESUMED',
  FINISHED: 'FINISHED',
  ORDER_PLACED: 'ORDER_PLACED',
  ORDER_REFUNDED: 'ORDER_REFUNDED',
};

exports.cSubscriptionCustomerTransactionError = {
  INVALID_SUBSCRIPTION: 'INVALID_SUBSCRIPTION',
  PER_DAY_LIMIT_EXCEED: 'PER_DAY_LIMIT_EXCEED',
  PER_ORDER_LIMIT_EXCEED: 'PER_ORDER_LIMIT_EXCEED',
  INVALID_MENU_ITEM: 'INVALID_MENU_ITEM',
  INVALID_MENU_ITEM_OPTION: 'INVALID_MENU_ITEM_OPTION',
};
