exports.CSubscriptionWeeklyOfferSaveError = {
  INVALID_BRAND: 'INVALID_BRAND',
  INVALID_COUNTRY: 'INVALID_COUNTRY',
  UNAUTHORIZED_PROCESS: 'UNAUTHORIZED_PROCESS',
  SORT_ORDER_ALREADY_EXIST: 'SORT_ORDER_ALREADY_EXIST'
};
