exports.saveCarouselItemErrorEnum = {
  NOT_EXIST: 'NOT_EXIST',
  MISSING_ARGUMENT: 'MISSING_ARGUMENT',
  SORT_ORDER_EXIST: 'SORT_ORDER_EXIST',
  INVALID_SECTION_ID: 'INVALID_SECTION_ID',
  ID_AND_SETTING_ID_BOTH_REQUIRED_FOR_UPDATE: 'ID_AND_SETTING_ID_BOTH_REQUIRED_FOR_UPDATE'
};

exports.saveCarouselItemTypeEnum = {
  CAROUSEL_ITEM: 'CAROUSEL_ITEM',
  CAROUSEL_ITEM_SETTING: 'CAROUSEL_ITEM_SETTING',
  SECTION_ID: 'INVALID_SECTION_ID'
};


exports.carouselItemStatusEnum = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DELETED: 'DELETED',
};
