exports.viewType = {
  FAQ: 'FAQ',
  HOW_IT_WORKS: 'HOW_IT_WORKS'
};

exports.featureOfContent = {
  SUBSCRIPTION: 'SUBSCRIPTION',
  DISCOVERY_CREDITS: 'DISCOVERY_CREDITS'
};

exports.contentStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DELETED: 'DELETED'
};

exports.commonContentError = {
  INVALID_COMMON_CONTENT_CATEGORY: 'INVALID_COMMON_CONTENT_CATEGORY',
  COMMON_CONTENT_NOT_FOUND: 'COMMON_CONTENT_NOT_FOUND',
  CONTENT_NOT_UPDATED: 'CONTENT_NOT_UPDATED'
};
