exports.otpCodeViewRequestError = {
  NOT_EXISTING_CUSTOMER: 'NOT_EXISTING_CUSTOMER',
  NO_ACTIVE_OTP_FOUND: 'NO_ACTIVE_OTP_FOUND',
  UNAUTHORIZED_ADMIN: 'UNAUTHORIZED_ADMIN',
};
exports.otpRateLimitResetRequestError = {
  SERVICE_ERROR: 'SERVICE_ERROR',
};
exports.customerRequestEmailVerificationError = {
  MAIL_SENDING_ERROR: 'MAIL_SENDING_ERROR',
  UNKNOWN_STATUS: 'UNKNOWN_STATUS',
  SERVICE_ERROR: 'SERVICE_ERROR',
};

exports.OTPProviders = {
  KARIX: 'KARIX',
  UNIFONIC: 'UNIFONIC',
  CEQUENS: 'CEQUENS',
  VICTORY_LINK: 'VICTORY_LINK',
  MOCK: 'MOCK',
  UNIFONIC_WHATSAPP: 'UNIFONIC_WHATSAPP'
};

exports.OTPTypes = {
  SMS: 'SMS',
  VOICE: 'VOICE',
};

exports.OTPOperationTypes = {
  REQUEST_SIGNUP_OTP: 'REQUEST_SIGNUP_OTP',
  REQUEST_SIGNUP_OTP_VOICE: 'REQUEST_SIGNUP_OTP_VOICE',
  REQUEST_LOGIN_OTP: 'REQUEST_LOGIN_OTP',
  REQUEST_LOGIN_OTP_VOICE: 'REQUEST_LOGIN_OTP_VOICE',
  VALIDATE_SIGNUP_OTP: 'VALIDATE_SIGNUP_OTP',
  VALIDATE_LOGIN_OTP: 'VALIDATE_LOGIN_OTP',
  VALIDATION_FAIL: 'VALIDATION_FAIL',
  DELIVERY_REPORT_CALLBACK: 'DELIVERY_REPORT_CALLBACK',
};

exports.userTypes = {
  CUSTOMER: 'CUSTOMER',
};

exports.smsRequestError = {
  COUNTRY_IS_NOT_AVAILABLE: 'COUNTRY_IS_NOT_AVAILABLE',
  SERVICE_ERROR: 'SERVICE_ERROR',
  INVALID_SMS_PROVIDER: 'INVALID_SMS_PROVIDER',
  INVALID_PHONE_NUMBER: 'INVALID_PHONE_NUMBER',
};

exports.smsSendStatus = {
  SENT: 'SENT',
  FAILED: 'FAILED'
};

exports.smsOperationType = {
  DRIVER: 'DRIVER',
  ECOM: 'ECOM'
};

exports.providerPrioties = {
  PRIMARY: 'PRIMARY',
  SECONDARY: 'SECONDARY'
};
