exports.stampRewardRedemptionItemError = {
  INVALID_MENU_ITEM: 'INVALID_MENU_ITEM',
  INVALID_REDEMPTION_ITEM: 'INVALID_REDEMPTION_ITEM',
  INVALID_INPUT: 'INVALID_INPUT',
  UNAUTHORIZED_ADMIN: 'UNAUTHORIZED_ADMIN',
  TRANSACTIONAL_ERROR: 'TRANSACTIONAL_ERROR',
};
