exports.badgeStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
};

exports.badgeSaveError = {
  TRANSACTIONAL_ERROR: 'TRANSACTIONAL_ERROR',
  UNAUTHORIZED_PROCESS: 'UNAUTHORIZED_PROCESS',
  INVALID_BADGE_ID: 'INVALID_BADGE_ID',
  BADGE_MUST_HAVE_LEAST_ONE_ATTRIBUTE: 'BADGE_MUST_HAVE_LEAST_ONE_ATTRIBUTE',
  BADGE_TEXT_COLOR_MUST_BE_REQUIRED: 'BADGE_TEXT_COLOR_MUST_BE_REQUIRED',
  INVALID_TEXT_COLOR_CODE: 'INVALID_TEXT_COLOR_CODE',
  INVALID_BACKGROUND_COLOR_CODE: 'INVALID_BACKGROUND_COLOR_CODE',
  THE_BADGE_CANNOT_ASSOCIATE_ANY_OBJECT: 'THE_BADGE_CANNOT_ASSOCIATE_ANY_OBJECT',
  INVALID_SUBSCRIPTION_ID: 'INVALID_SUBSCRIPTION_ID',
  RELATION_ID_LIST_CANNOT_BE_EMPYT: 'RELATION_ID_LIST_CANNOT_BE_EMPYT',
  INVALID_REL_ID: 'INVALID_REL_ID',
};

exports.badgeTypes = {
  SUBSCRIPTION_MOST_POPULAR: 'SUBSCRIPTION_MOST_POPULAR',
  SUBSCRIPTION_TYPE_CUP: 'SUBSCRIPTION_TYPE_CUP',
  SUBSCRIPTION_TYPE_BUNDLE: 'SUBSCRIPTION_TYPE_BUNDLE',
  SUBSCRIPTION_TYPE_MENU_CUP: 'SUBSCRIPTION_TYPE_MENU_CUP',
  SUBSCRIPTION_TYPE_MENU_BUNDLE: 'SUBSCRIPTION_TYPE_MENU_BUNDLE',
};
