exports.MaintenanceError = {
  INVALID_BRAND: 'INVALID_BRAND',
  INVALID_BRAND_LOCATION: 'INVALID_BRAND_LOCATION',
  INVALID_BRAND_LOCATION_EMAIL: 'INVALID_BRAND_LOCATION_EMAIL',
  INVALID_BRAND_LOCATION_PHONE: 'INVALID_BRAND_LOCATION_PHONE',
  MISSING_BRAND_LOCATION_LONGITUDE_LATITUDE: 'MISSING_BRAND_LOCATION_LONGITUDE_LATITUDE',
  ALREADY_ENABLE: 'ALREADY_ENABLE',
  DISABLE_MAINTENANCE_FOR_BRAND: 'DISABLE_MAINTENANCE_FOR_BRAND',
  DISABLE_MAINTENANCE_FOR_COUNTRY: 'DISABLE_MAINTENANCE_FOR_COUNTRY',
  BRAND_LOCATION_NOT_REGISTERED: 'BRAND_LOCATION_NOT_REGISTERED',
  MAINTENANCE_REQUEST_ALREADY_EXIST: 'MAINTENANCE_REQUEST_ALREADY_EXIST',
  AREA_LIST_ERROR: 'AREA_LIST_ERROR',
  INVALID_AREA: 'INVALID_AREA',
  AVAILABLE_SUB_SERVICE_LIST_ERROR: 'AVAILABLE_SUB_SERVICE_LIST_ERROR',
  INVALID_SUB_SERVICE: 'INVALID_SUB_SERVICE',
  ASSESSMENT_ALREADY_GENERATE: 'ASSESSMENT_ALREADY_GENERATE',
  ASSESSMENT_GENERATE_ERROR: 'ASSESSMENT_GENERATE_ERROR',
  INVALID_ASSESSMENT: 'INVALID_ASSESSMENT',
  INACTIVE_ASSESSMENT: 'INACTIVE_ASSESSMENT',
  TICKET_GENERATE_ERROR: 'TICKET_GENERATE_ERROR',
  USER_NOT_REGISTERED: 'USER_NOT_REGISTERED',
  TRANSACTIONAL_ERROR: 'TRANSACTIONAL_ERROR',
  UNAUTHORIZED_PROCESS: 'UNAUTHORIZED_PROCESS',
};

exports.MaintenanceRequestStatus = {
  REQUESTED: 'REQUESTED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
};

exports.MaintenanceUserStatus = {
  INIT: 'INIT',
  REQUESTED: 'REQUESTED',
  REGISTERED: 'REGISTERED',
  BLOCKED: 'BLOCKED',
  INACTIVE: 'INACTIVE',
};

exports.MaintenanceAssessmentStatus = {
  INIT: 'INIT',
  REQUESTED: 'REQUESTED',
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
};
