exports.stampRewardStatus = {
  ENABLE: 'ENABLE',
  DISABLE: 'DISABLE',
}

exports.stampRewardProcessTypes = {
  ADD: 'ADD',
  REMOVE: 'REMOVE',
}

exports.stampRewardCustomerError = {
  INVALID_CUSTOMER: 'INVALID_CUSTOMER',
  PROGRAM_DISABLE: 'PROGRAM_DISABLE',
  INVALID_ORDER: 'INVALID_ORDER',
  ORDER_CAN_NOT_FOUND_REDEMPTION_ORDER_LIST: 'ORDER_CAN_NOT_FOUND_REDEMPTION_ORDER_LIST',
  STAMP_IS_ALREADY_REMOVED_REDEMPTION_ORDER_LIST: 'STAMP_IS_ALREADY_REMOVED_REDEMPTION_ORDER_LIST',
  CUSTOMER_HAS_NOT_STAMP_FOR_REMOVE_PROCESS: 'CUSTOMER_HAS_NOT_STAMP_FOR_REMOVE_PROCESS',
  ORDER_HAS_NOT_REDEMPTION_ITEMS: 'ORDER_HAS_NOT_REDEMPTION_ITEMS',
  STAMP_REWARD_ALREADY_REFUND: 'STAMP_REWARD_ALREADY_REFUND',
  CUSTOMER_ALREADY_HAS_MAX_STAMP_COUNT: 'CUSTOMER_ALREADY_HAS_MAX_STAMP_COUNT',
  ORDER_IS_ALREADY_ADDED_TO_REDEMPTION_LIST: 'ORDER_IS_ALREADY_ADDED_TO_REDEMPTION_LIST',
  UNAUTHORIZED_PROCESS: 'UNAUTHORIZED_PROCESS',
};
