exports.cSubscriptionCustomerStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
};

exports.CSubscriptionStatusInfo = {
  NO_SUBSCRIPTION: 'NO_SUBSCRIPTION',
  ACTIVE_SUBSCRIPTION: 'ACTIVE_SUBSCRIPTION',
  INACTIVE_SUBSCRIPTION: 'INACTIVE_SUBSCRIPTION'
};
