exports.DriverSaveError = {
  INVALID_PHONE_NUMBER: 'INVALID_PHONE_NUMBER',
  INVALID_FIRST_NAME: 'INVALID_FIRST_NAME',
  INVALID_LAST_NAME: 'INVALID_LAST_NAME',
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_PHONE_COUNTRY: 'INVALID_PHONE_COUNTRY',
  DRIVER_ALREADY_EXIST: 'DRIVER_ALREADY_EXIST'
};

exports.DriverBranchSaveError = {
  INVALID_DRIVER: 'INVALID_DRIVER',
  INVALID_BRANCH: 'INVALID_BRANCH',
  INVALID_INPUT: 'INVALID_INPUT',
  BRANCH_ALREADY_EXIST: 'BRANCH_ALREADY_EXIST',
};

exports.DriverDeleteError = {
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
  INVALID_DRIVER: 'INVALID_DRIVER',
};
