exports.orderCreateError = {
  // Brand id provided is invalid
  INVALID_BRAND_LOCATION: 'INVALID_BRAND_LOCATION',
  // An menu item id is invalid
  INVALID_MENU_ITEM: 'INVALID_MENU_ITEM',
  // A menu item option id is invalid
  INVALID_MENU_ITEM_OPTION: 'INVALID_MENU_ITEM_OPTION',
  INVALID_MENU_ITEM_OPTION_PRICE: 'INVALID_MENU_ITEM_OPTION_PRICE',
  // Outside of the available requested fulfillment hours
  OUTSIDE_AVAILABLE_HOURS: 'OUTSIDE_AVAILABLE_HOURS',
  // Quantity must be larger than 0
  ZERO_QUANTITY_REQUESTED: 'ZERO_QUANTITY_REQUESTED',
  // Unable to initiate merchant transaction
  MERCHANT_INITIALIZATION_ERROR: 'MERCHANT_INITIALIZATION_ERROR',
  // Invalid Customer (does not exist)
  INVALID_CUSTOMER: 'INVALID_CUSTOMER',
  // Need to provide either tower or addressId
  ADDRESS_REQUIRED: 'ADDRESS_REQUIRED',
  // Invalid tower delivery info
  INVALID_TOWER_DELIVERY: 'INVALID_TOWER_DELIVERY',
  // Wrong Customer Address (address does not belong to customer)
  WRONG_CUSTOMER_ADDRESS: 'WRONG_CUSTOMER_ADDRESS',
  // Invalid Customer Address (Does not exist)
  INVALID_CUSTOMER_ADDRESS: 'INVALID_CUSTOMER_ADDRESS',
  VEHICLE_REQUIRED: 'VEHICLE_REQUIRED',
  INVALID_CUSTOMER_VEHICLE: 'INVALID_CUSTOMER_VEHICLE',
  WRONG_CUSTOMER_VEHICLE: 'WRONG_CUSTOMER_VEHICLE',
  // Brand Location Not Accepting Orders
  BRAND_LOCATION_NOT_ACCEPTING_ORDERS: 'BRAND_LOCATION_NOT_ACCEPTING_ORDERS',
  // Invalid or Expired Coupon used
  INVALID_COUPON: 'INVALID_COUPON',
  // Customer loyalty credit balance is insufficient for this order
  INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS',
  // attempting a cashOnDelivery order when the brand doesn't accept cash orders
  BRAND_DOESNT_ACCEPT_CASH: 'BRAND_DOESNT_ACCEPT_CASH',
  // try to use a perk that doesn't exist or is unavailable
  INVALID_PERK: 'INVALID_PERK',
  INVALID_GIFT_CARD: 'INVALID_GIFT_CARD',
  INSUFFICIENT_GIFT_CARD_CREDITS: 'INSUFFICIENT_GIFT_CARD_CREDITS',
  INVALID_GIFT_CARD_CURRENCY: 'INVALID_GIFT_CARD_CURRENCY',
  PAYMENT_METHOD_REQUIRED: 'PAYMENT_METHOD_REQUIRED',
  INSUFFICIENT_DELIVERY_ORDER_VALUE: 'INSUFFICIENT_DELIVERY_ORDER_VALUE',
  INSUFFICIENT_EXPRESS_DELIVERY_ORDER_VALUE:
    'INSUFFICIENT_EXPRESS_DELIVERY_ORDER_VALUE',
  ORDER_ALREADY_PROCESSED: 'ORDER_ALREADY_PROCESSED',
  SIRI_NOT_SUPPORTED_THIS_PAYMENT_SCHEME: 'SIRI_NOT_SUPPORTED_THIS_PAYMENT_SCHEME',
  MENU_ITEM_OUT_OF_STOCK: 'MENU_ITEM_OUT_OF_STOCK',
  INVALID_FULFILLMENT_TYPE: 'INVALID_FULFILLMENT_TYPE',
  ADDRESS_OUT_OF_DELIVERY_ZONE: 'ADDRESS_OUT_OF_DELIVERY_ZONE',
  MENU_ITEM_OPTION_NOT_AVAILABLE: 'MENU_ITEM_OPTION_NOT_AVAILABLE',
  MISSING_PRIMARY_MENU_ITEM_OPTION: 'MISSING_PRIMARY_MENU_ITEM_OPTION',
  I_AM_HERE_NOT_SUPPORTED: 'I_AM_HERE_NOT_SUPPORTED',
  INVALID_ARRIVAL_TIME: 'INVALID_ARRIVAL_TIME',
  INVALID_BRAND: 'INVALID_BRAND',
  MENU_ITEM_OPTION_DUBLICATE_IN_ITEM: 'MENU_ITEM_OPTION_DUBLICATE_IN_ITEM',
  MULTIBLE_OPTION_CAN_NOT_SELECTED: 'MULTIBLE_OPTION_CAN_NOT_SELECTED',
  OPTION_CAN_NOT_FOUND_IN_ITEM: 'OPTION_CAN_NOT_FOUND_IN_ITEM',
};

exports.orderFulfillmentTypes = {
  PICKUP: 'PICKUP',
  CAR: 'CAR',
  DELIVERY: 'DELIVERY',
  // HOSPITAL: 'HOSPITAL',
  // CLASS: 'CLASS',
  // OFFICE: 'OFFICE',
  // AIRPORT: 'AIRPORT',
  EXPRESS_DELIVERY: 'EXPRESS_DELIVERY', // merging office, airport, hospital, class
};

exports.skipOrderRatingError = {
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  WRONG_RATING_STATUS: 'WRONG_RATING_STATUS'
};

exports.orderSetRefundReason = {
  VENDOR_RELATED: 'VENDOR_RELATED',
  CUSTOMER_RELATED: 'CUSTOMER_RELATED',
  COFE_RELATED: 'COFE_RELATED',
  DELIVERY_PARTNER: 'DELIVERY_PARTNER'
};
