exports.cSubscriptionBrandStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DELETED: 'DELETED'
};

exports.cSubscriptionBrandSaveError = {
  INVALID_SUBSCRIPTION: 'INVALID_SUBSCRIPTION',
  INVALID_BRAND: 'INVALID_BRAND',
  INVALID_STATUS: 'INVALID_STATUS',
  NOT_SUPPORTED: 'NOT_SUPPORTED',
  INVALID_COUNTRY: 'INVALID_COUNTRY'
};
