exports.cSubscriptionMenuItemOptionsDeleteError = {
  INVALID_ID: 'INVALID_ID',
  INVALID_SUBSCRIPTION_ID: 'INVALID_SUBSCRIPTION_ID',
  INVALID_CSUBSCRIPTION_MENU_ITEM_ID: 'INVALID_CSUBSCRIPTION_MENU_ITEM_ID',
  UNAUTHORIZED_PROCESS: 'UNAUTHORIZED_PROCESS'
};
