exports.tagRelationSaveError = {
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_TAG: 'INVALID_TAG',
  INVALID_BRAND_LOCATION: 'INVALID_BRAND_LOCATION',
  BRAND_HAS_NOT_BRAND_LOCATION: 'BRAND_HAS_NOT_BRAND_LOCATION',
  SHOULD_BE_SELECTED_A_BRAND_LOCATION: 'SHOULD_BE_SELECTED_A_BRAND_LOCATION',
  INVALID_BRAND_LOCATION_LIST: 'INVALID_BRAND_LOCATION_LIST',
  INVALID_MENU_ITEM: 'INVALID_MENU_ITEM',
  UNEXPECTED_INPUT: 'UNEXPECTED_INPUT',
  ALREADY_SAVED: 'ALREADY_SAVED',
};

exports.tagRelationType = {
  MENU_ITEM: 'MENU_ITEM',
  BRAND_LOCATION: 'BRAND_LOCATION',
};
