exports.BrandLocationAvailabilityError = {
  INVALID_BRAND: 'INVALID_BRAND',
  INVALID_BRAND_LOCATION: 'INVALID_BRAND_LOCATION',
  CAN_NOT_FOUND_AVAILABILITY: 'CAN_NOT_FOUND_AVAILABILITY',
  BRAND_LOCATION_ID_NOT_MATCHED: 'BRAND_LOCATION_ID_NOT_MATCHED',
  MINIMUM_ONE_FULFILLMENT_TYPE_MUST_BE_CHOSEN: 'MINIMUM_ONE_FULFILLMENT_TYPE_MUST_BE_CHOSEN',
  PICKUP_FULFILLMENT_MUST_BE_ACTIVE_FOR_AVAILABILITY: 'PICKUP_FULFILLMENT_MUST_BE_ACTIVE_FOR_AVAILABILITY',
  CAR_FULFILLMENT_MUST_BE_ACTIVE_FOR_AVAILABILITY: 'CAR_FULFILLMENT_MUST_BE_ACTIVE_FOR_AVAILABILITY',
  DELIVERY_FULFILLMENT_MUST_BE_ACTIVE_FOR_AVAILABILITY: 'DELIVERY_FULFILLMENT_MUST_BE_ACTIVE_FOR_AVAILABILITY',
  EXPRESS_DELIVERY_FULFILLMENT_MUST_BE_ACTIVE_FOR_AVAILABILITY: 'EXPRESS_DELIVERY_FULFILLMENT_MUST_BE_ACTIVE_FOR_AVAILABILITY',
  ALREADY_REMOVED_AVAILABILITY: 'ALREADY_REMOVED_AVAILABILITY',
  BRAND_LOCATION_ALREAD_CLOSED_FOR_BUSY_STATUS: 'BRAND_LOCATION_ALREAD_CLOSED_FOR_BUSY_STATUS',
  TRANSACTIONAL_ERROR: 'TRANSACTIONAL_ERROR',
  UNAUTHORIZED_PROCESS: 'UNAUTHORIZED_PROCESS',
};

exports.BrandLocationBusyInputType = {
  MIN_15: 'MIN_15',
  MIN_30: 'MIN_30',
  MIN_60: 'MIN_60',
  INDEFINITELY: 'INDEFINITELY',
};
