exports.cSubscriptionOrderCreateError = {
  INVALID_CUSTOMER: 'INVALID_CUSTOMER',
  INVALID_SUBSCRIPTION: 'INVALID_SUBSCRIPTION',
  INVALID_SUBSCRIPTION_CUSTOMER: 'INVALID_SUBSCRIPTION_CUSTOMER',
  INVALID_ITEM: 'INVALID_ITEM',
  ALREADY_EXIST_SUBSCRIPTION: 'ALREADY_EXIST_SUBSCRIPTION',
  PAYMENT_METHOD_REQUIRED: 'PAYMENT_METHOD_REQUIRED',
  MERCHANT_INITIALIZATION_ERROR: 'MERCHANT_INITIALIZATION_ERROR',
  CASH_NOT_AVAILABLE: 'CASH_NOT_AVAILABLE',
  PAYMENT_FAILURE: 'PAYMENT_FAILURE',
  UNAUTHORIZED_PROCESS: 'UNAUTHORIZED_PROCESS',
  PAYMENT_METHOD_INVALID_FOR_AUTO_RENEWAL:
    'PAYMENT_METHOD_INVALID_FOR_AUTO_RENEWAL',
  INVALID_COUPON: 'INVALID_COUPON',
  NON_EXISTING_CUSTOMER_CARD: 'NON_EXISTING_CUSTOMER_CARD',
  INVALID_COUPON_OR_INAPPLICABLE_PAYMENT_METHOD:
    'INVALID_COUPON_OR_INAPPLICABLE_PAYMENT_METHOD',
  INAPPLICABLE_BANK_OR_CARD_FOR_COUPON: 'INAPPLICABLE_BANK_OR_CARD_FOR_COUPON',
  INAPPLICABLE_VENDOR_FOR_COUPON: 'INAPPLICABLE_VENDOR_FOR_COUPON',
  COUPON_ALREADY_CONSUMED_BY_VENDOR: 'COUPON_ALREADY_CONSUMED_BY_VENDOR',
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
  CAN_NOT_BE_USED_WITH_REWARD_DISCOUNT: 'CAN_NOT_BE_USED_WITH_REWARD_DISCOUNT',
  CAN_NOT_BE_USED_WITH_DISCOVERY_POINT: 'CAN_NOT_BE_USED_WITH_DISCOVERY_POINT',
  INVALID_COUPON_TYPE_FOR_SUBSCRIPTION: 'INVALID_COUPON_TYPE_FOR_SUBSCRIPTION',
  INVALID_PAYMENT_METHOD_FOR_SUBSCRIPTION: 'INVALID_PAYMENT_METHOD_FOR_SUBSCRIPTION',
  INVALID_COUPON_PROMO_TYPE: 'INVALID_COUPON_PROMO_TYPE',
  INVALID_COUPON_REFERRAL_CODE_CAN_NOT_BE_SAME_COUPON_CODE: 'INVALID_COUPON_REFERRAL_CODE_CAN_NOT_BE_SAME_COUPON_CODE',
  INVALID_COUPON_CUSTOMER_REDEMPTION_LIMIT_EXCEEDED: 'INVALID_COUPON_CUSTOMER_REDEMPTION_LIMIT_EXCEEDED',
  INVALID_COUPON_FOR_USER: 'INVALID_COUPON_FOR_USER',
  INVALID_COUPON_FIRST_ORDER_REDEMPTION_LIMIT_EXCEEDED: 'INVALID_COUPON_FIRST_ORDER_REDEMPTION_LIMIT_EXCEEDED',
};

exports.cSubscriptionOrderStatus = {
  INITIATED: 'INITIATED',
  FAILED: 'FAILED',
  COMPLETED: 'COMPLETED',
};
