exports.stampRewardLogType = {
  CREATE_ORDER_WITH_REDEMPTION_ITEM: 'CREATE_ORDER_WITH_REDEMPTION_ITEM',
  CREATE_ORDER_WITH_ELIGIBLE_ITEM: 'CREATE_ORDER_WITH_ELIGIBLE_ITEM',
  REFUND_STAMP_REWARD_PERK: 'REFUND_STAMP_REWARD_PERK',
  REMOVE_STAMP_WITH_REDEMPTION_ITEM: 'REMOVE_STAMP_WITH_REDEMPTION_ITEM',
  ELIGIBLE_ITEMS_UPDATE: 'ELIGIBLE_ITEMS_UPDATE',
  REDEMPTION_ITEMS_UPDATE: 'REDEMPTION_ITEMS_UPDATE',
};
