exports.paymentMethodError = {
  INVALID_PAYMENT_PROVIDER_ID: 'INVALID_PAYMENT_PROVIDER_ID',
  UNDEFINED_PAYMENT_RROVIDER: 'UNDEFINED_PAYMENT_RROVIDER',
  INVALID_PAYMENT_PROVIDER: 'INVALID_PAYMENT_PROVIDER',
  COUNTRY_NOT_MATCHED_PAYMENT_PROVIDER: 'COUNTRY_NOT_MATCHED_PAYMENT_PROVIDER',
  APPLE_PAY_ALREADY_ENABLE_ANOTHER_PROVIDER: 'APPLE_PAY_ALREADY_ENABLE_ANOTHER_PROVIDER',
  GOOGLE_PAY_ALREADY_ENABLE_ANOTHER_PROVIDER: 'GOOGLE_PAY_ALREADY_ENABLE_ANOTHER_PROVIDER',
  KNET_ALREADY_ENABLE_ANOTHER_PROVIDER: 'KNET_ALREADY_ENABLE_ANOTHER_PROVIDER',
  VISA_MASTER_ALREADY_ENABLE_ANOTHER_PROVIDER: 'VISA_MASTER_ALREADY_ENABLE_ANOTHER_PROVIDER',
  MADA_ALREADY_ENABLE_ANOTHER_PROVIDER: 'MADA_ALREADY_ENABLE_ANOTHER_PROVIDER',
  STC_ALREADY_ENABLE_ANOTHER_PROVIDER: 'STC_ALREADY_ENABLE_ANOTHER_PROVIDER',
  CARD_SAVED_ALREADY_ENABLE_ANOTHER_PROVIDER: 'CARD_SAVED_ALREADY_ENABLE_ANOTHER_PROVIDER',
  KNET_CAN_NOT_ENABLE_FOR_CHECKOUT_PROVIDER: 'KNET_CAN_NOT_ENABLE_FOR_CHECKOUT_PROVIDER',
  STC_CAN_NOT_ENABLE_FOR_CHECKOUT_PROVIDER: 'STC_CAN_NOT_ENABLE_FOR_CHECKOUT_PROVIDER',
  MADA_CAN_NOT_ENABLE_FOR_CHECKOUT_PROVIDER: 'MADA_CAN_NOT_ENABLE_FOR_CHECKOUT_PROVIDER',
  CARD_SAVED_CAN_NOT_ENABLE_FOR_MY_FATOORAH_PROVIDER: 'CARD_SAVED_CAN_NOT_ENABLE_FOR_MY_FATOORAH_PROVIDER',
  KNET_CAN_NOT_ENABLE_FOR_MOBILE_EXPRESS_PROVIDER: 'KNET_CAN_NOT_ENABLE_FOR_MOBILE_EXPRESS_PROVIDER',
  STC_CAN_NOT_ENABLE_FOR_MOBILE_EXPRESS_PROVIDER: 'STC_CAN_NOT_ENABLE_FOR_MOBILE_EXPRESS_PROVIDER',
  MADA_CAN_NOT_ENABLE_FOR_MOBILE_EXPRESS_PROVIDER: 'MADA_CAN_NOT_ENABLE_FOR_MOBILE_EXPRESS_PROVIDER',
  CARD_SAVED_NOT_ENABLE_FOR_COUNTRY: 'CARD_SAVED_NOT_ENABLE_FOR_COUNTRY',
  INVALID_PAYMENT_METHOD: 'INVALID_PAYMENT_METHOD',
  UNDEFINED_PAYMENT_METHOD: 'UNDEFINED_PAYMENT_METHOD',
  PROVIDER_NAME_ALREADY_USED: 'PROVIDER_NAME_ALREADY_USED',
  INVALID_COUNTRY_ID: 'INVALID_COUNTRY_ID',
  INVALID_PAYMENT_METHOD_ID: 'INVALID_PAYMENT_METHOD_ID',
  PAYMENT_METHOD_ALREADY_EXIST_FOR_THIS_PROVIDER: 'PAYMENT_METHOD_ALREADY_EXIST_FOR_THIS_PROVIDER',
  INVALID_PAYMENT_METHOD_NOT_MATCHED_COUNTRY: 'INVALID_PAYMENT_METHOD_NOT_MATCHED_COUNTRY',
  TRANSACTIONAL_ERROR: 'TRANSACTIONAL_ERROR',
  UNAUTHORIZED_PROCESS: 'UNAUTHORIZED_PROCESS',
};

exports.paymentMethodStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
};

exports.availablePaymentOption = {
  APPLE_PAY: 'APPLE_PAY',
  GOOGLE_PAY: 'GOOGLE_PAY',
  KNET: 'KNET',
  VISA_MASTER: 'VISA_MASTER',
  AMEX: 'AMEX',
  MADA: 'MADA',
  STC: 'STC',
  CARD_SAVED: 'CARD_SAVED',
};

exports.paymentProviderEnum = {
  MY_FATOORAH: 'MY_FATOORAH',
  CHECKOUT: 'CHECKOUT',
  MOBILE_EXPRESS: 'MOBILE_EXPRESS',
};
