exports.saveIconButtonErrorEnum = {
  NOT_EXIST: 'NOT_EXIST',
  MISSING_ARGUMENT: 'MISSING_ARGUMENT',
  SORT_ORDER_EXIST: 'SORT_ORDER_EXIST',
  ALREADY_EXIST_IMAGE_TYPE_AND_DEEP_LINK: 'ALREADY_EXIST_IMAGE_TYPE_AND_DEEP_LINK',
  INVALID_SECTION_ID: 'INVALID_SECTION_ID',
  INVALID_SPAN_SIZE: 'INVALID_SPAN_SIZE',
};

exports.SaveIconButtonItemTypeEnum = {
  ICON_BUTTON_ITEM: 'ICON_BUTTON_ITEM',
  ICON_BUTTON_ITEM_SETTING: 'ICON_BUTTON_ITEM_SETTING',
  SECTION_ID: 'SECTION_ID'
};

exports.tagRelationType = {
  MENU_ITEM: 'MENU_ITEM',
  BRAND_LOCATION: 'BRAND_LOCATION',
  ICON_ITEM: 'ICON_ITEM'

};

exports.IconItemStatusEnum = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DELETED: 'DELETED'
};
