exports.orderRatingWithDetailSaveError = {
  NOT_MATCHED_CUSTOMER: 'NOT_MATCHED_CUSTOMER',
  INVALID_ORDER_SET_ID: 'INVALID_ORDER_SET_ID',
  ALREADY_RATED_ORDER: 'ALREADY_RATED_ORDER',
  ORDER_NOT_COMPLETED: 'ORDER_NOT_COMPLETED',
  INVALID_RATING: 'INVALID_RATING',
  INVALID_OVERALL_QUESTION: 'INVALID_OVERALL_QUESTION',
  RATEABLE_TIME_OVER: 'RATEABLE_TIME_OVER',
  INVALID_COMMENT: 'INVALID_COMMENT',
  INVALID_QUESTION: 'INVALID_QUESTION',
};
