exports.tagSaveError = {
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_FIELD_ID: 'MISSING_FIELD_ID',
  MISSING_FIELD_START_TIME: 'MISSING_FIELD_START_TIME',
  MISSING_FIELD_END_TIME: 'MISSING_FIELD_END_TIME',
  START_TIME_MUST_BE_BEFORE_END_TIME: 'START_TIME_MUST_BE_BEFORE_END_TIME',
  INTERSECTION_TIME_IN_TAG_SCHEDULES: 'INTERSECTION_TIME_IN_TAG_SCHEDULES',
  MISSING_FIELD_SCHEDULE_ID: 'MISSING_FIELD_SCHEDULE_ID',
  MISSING_FIELD_SCHEDULE_ID_FOR_DELETING_SCHEDULE: 'MISSING_FIELD_SCHEDULE_ID_FOR_DELETING_SCHEDULE',
  MISSING_TAG_SCHEDULE_PARAMETERS: 'MISSING_TAG_SCHEDULE_PARAMETERS',
  MISSING_SCHEDULES_IF_IS_SCHEDULED_PASSED: 'MISSING_SCHEDULES_IF_IS_SCHEDULED_PASSED',
  SCHEDULE_MUST_BE_ENTERING: 'SCHEDULE_MUST_BE_ENTERING',
  TAG_AND_TAG_SCHEDULE_NOT_MATCHED: 'TAG_AND_TAG_SCHEDULE_NOT_MATCHED',
};

exports.tagScheduleStatus = {
  ACTIVE: 'ACTIVE',
  DELETED: 'DELETED',
};
