exports.builtinComponents = {
  EXPRESS_ZONE: 'EXPRESS_ZONE',
  BRAND_LOCATION: 'BRAND_LOCATION',
  BRAND: 'BRAND',
  SUBSCRIPTION: 'SUBSCRIPTION',
};

exports.horizontalCardListItemStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DELETED: 'DELETED',
};

exports.horizontalCardListItemType = {
  BRAND_LOCATION: 'BRAND_LOCATION',
  BRAND: 'BRAND',
  SUBSCRIPTION: 'SUBSCRIPTION',
};

exports.horizontalCardListItemError = {
  INVALID_SECTION: 'INVALID_SECTION',
  SECTION_TYPE_CAN_NOT_SUPPORT_HORIZONTAL_CARD: 'SECTION_TYPE_CAN_NOT_SUPPORT_HORIZONTAL_CARD',
  INVALID_BRAND: 'INVALID_BRAND',
  INVALID_BRAND_LOCATION: 'INVALID_BRAND_LOCATION',
  INVALID_SUBSCRIPTION_BRAND: 'INVALID_SUBSCRIPTION_BRAND',
  TRANSACTIONAL_ERROR: 'TRANSACTIONAL_ERROR',
  UNAUTHORIZED_PROCESS: 'UNAUTHORIZED_PROCESS',
};
