exports.tagSaveError = {
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_FIELD_NAME: 'MISSING_FIELD_NAME',
  MISSING_FIELD_DESCRIPTION: 'MISSING_FIELD_DESCRIPTION',
  NAME_ALREADY_EXIST: 'NAME_ALREADY_EXIST',
  MISSING_FIELD_TYPE: 'MISSING_FIELD_TYPE',
  INVALID_TAG_TYPE: 'INVALID_TAG_TYPE',
  MISSING_TEXT_COLOR: 'MISSING_TEXT_COLOR',
  MISSING_ICON_URL: 'MISSING_ICON_URL',
  MISSING_BACKGROUND_COLOR: 'MISSING_BACKGROUND_COLOR',
};

exports.tagType = {
  OFFER: 'OFFER',
  OTHER: 'OTHER'
};

exports.tagType = {
  OFFER: 'OFFER',
  OTHER: 'OTHER'
};
